### ISSUE TITLE
Nested powers

### ISSUE THREAD

**Issue by MeijisIrlnd** [NTDLS/CMathParser#3]
Yo, this thing is awesome, just doing some messing around with it now, this could very well be user error, but I found that `"sin(pow(10,2))"` gives me this error, but it works the other way round (`"pow(sin(10))"` for example), wondering if I'm just missing something or if something wacky is going on with powers in other functions!
Either way this is amazing, looking forward to messing around more with it!
(Edit, I did find a workaround by parsing the string for pow and solving that as a seperate expression!)
![image](https://user-images.githubusercontent.com/38221014/123278089-8f8b8800-d4fe-11eb-8a08-09a6ce2c129c.png)

**Comment by NTDLS** [comment]
> Yo, this thing is awesome, just doing some messing around with it now, this could very well be user error, but I found that `"sin(pow(10,2))"` gives me this error, but it works the other way round (`"pow(sin(10))"` for example), wondering if I'm just missing something or if something wacky is going on with powers in other functions!
> Either way this is amazing, looking forward to messing around more with it!
> (Edit, I did find a workaround by parsing the string for pow and solving that as a seperate expression!)
> ![image](https://user-images.githubusercontent.com/38221014/123278089-8f8b8800-d4fe-11eb-8a08-09a6ce2c129c.png)

Sorry for the delay! I'm really getting annoyed that I'm not getting notifications from this repo. Looking into this.

**Comment by NTDLS** [comment]
My apologies for the long resolution time, but this has been resolved. Please let me know if you have any further issues.

https://github.com/NTDLS/CMathParser/commit/cba29ff8e75d095e6aae1dba778c604da5c75780#diff-c3e8036ba35872b2d5cfb8e2b248c2fd3b3cd99986cb14063bb79f610bbfd3e0
