### ISSUE TITLE
Compiler Error C2440

### ISSUE THREAD

**Issue by gage-lodba** [NTDLS/CMathParser#4]
When trying to compile the code I am receiving `Compiler Error C2440` at: 
https://github.com/NTDLS/CMathParser/blob/ae5b5fec154379ae13ea8eeb47ffc0d8a365fc26/CMathParser.cpp#L720 https://github.com/NTDLS/CMathParser/blob/ae5b5fec154379ae13ea8eeb47ffc0d8a365fc26/CMathParser.cpp#L737-L748 https://github.com/NTDLS/CMathParser/blob/ae5b5fec154379ae13ea8eeb47ffc0d8a365fc26/CMathParser.cpp#L771-L776 `error C2440: '=': cannot convert from 'const char [2]' to 'char *'`

I am using Visual Studio C++20 but I get the same error switching from 20 to 17 or 14 so I am not sure how you are compiling this without any issues. If you have any workarounds for this I will gladly try them out, I just thought I would create this issue incase it's the compiler I am using or maybe some other issue.

**Comment by NTDLS** [comment]
I am compiling with `Microsoft Visual Studio Community 2019 Version 16.8.5` using build tools `Visual Studio 2019 (v142)`.

I'm not sure why this would be giving you issues but maybe you can try casting the expression?

`sOp = (char*)"-"; `

**Comment by gage-lodba** [comment]
That managed to fix it thanks! I think it may have something to do with c++ 20.
![image](https://user-images.githubusercontent.com/38990407/151906315-d08096d7-2b6e-45eb-bbef-0440e9f5c13e.png)

**Comment by NTDLS** [comment]
Excellent!!! Thank you for letting me know!
